"""
Generates a lightweight Product Requirements Document (PRD.md) from the
analysis results. This is template-driven (not an extra AI call) so it is
fast and deterministic.
"""
from datetime import date
from typing import List

from app.models.schemas import EngineeringTask, IssueCluster, SummaryStats


def build_prd_markdown(
    stats: SummaryStats,
    clusters: List[IssueCluster],
    tasks: List[EngineeringTask],
    pm_summary: str,
) -> str:
    top_clusters = clusters[:10]

    lines: List[str] = []
    lines.append("# Product Requirements Document")
    lines.append("")
    lines.append(f"_Generated by CursorPM on {date.today().isoformat()}_")
    lines.append("")
    lines.append("## 1. Executive Summary")
    lines.append("")
    lines.append(pm_summary)
    lines.append("")
    lines.append("## 2. Feedback Overview")
    lines.append("")
    lines.append(f"- Total reviews analyzed: **{stats.total_reviews}**")
    lines.append(f"- Critical issues: **{stats.critical_issues}**")
    lines.append(f"- High priority items (Critical + High): **{stats.high_priority}**")
    lines.append(f"- Bug reports: **{stats.bugs}**")
    lines.append(f"- Feature requests: **{stats.feature_requests}**")
    lines.append(f"- Performance issues: **{stats.performance_issues}**")
    lines.append("")
    lines.append("## 3. Top Issues by Priority")
    lines.append("")
    lines.append("| # | Issue | Category | Severity | Frequency | Priority Score |")
    lines.append("|---|-------|----------|----------|-----------|-----------------|")
    for idx, cluster in enumerate(top_clusters, start=1):
        lines.append(
            f"| {idx} | {cluster.issue} | {cluster.category.value} | {cluster.severity.value} "
            f"| {cluster.frequency} | {cluster.priority_score} |"
        )
    lines.append("")
    lines.append("## 4. Proposed Engineering Work")
    lines.append("")
    for task in tasks:
        lines.append(f"### {task.title}")
        lines.append("")
        lines.append(task.description)
        lines.append("")
        lines.append(f"- **Priority:** {task.priority.value}")
        lines.append(f"- **Story Points:** {task.story_points}")
        lines.append(f"- **Labels:** {', '.join(task.labels)}")
        lines.append("- **Acceptance Criteria:**")
        for criterion in task.acceptance_criteria:
            lines.append(f"  - {criterion}")
        lines.append("")
    lines.append("## 5. Recommendation")
    lines.append("")
    lines.append(
        "Prioritize the issues above the 'High' priority threshold in the next "
        "sprint. Re-run this analysis after shipping fixes to validate impact "
        "on sentiment and issue frequency."
    )
    lines.append("")

    return "\n".join(lines)
